# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Build.DefinitionName)_$(Date:yyyyMMdd))

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  major: 0
  minor: 0
  patch: $(Build.BuildID)
  buildVersion: $(major).$(minor).$(patch)
  system.debug: true
  moduleName: 'Elizium.FakeBuddy'

stages:
- stage: Build
  jobs:
    - job: Build
      steps:
      - powershell: ./bootstrap-and-build.ps1
        displayName: 'Bootstrap & Build'
      - powershell: ./check-module-built.ps1
        displayName: 'Check module built'
      - task: NuGetCommand@2
        inputs:
          command: 'pack'
          packagesToPack: '$(System.DefaultWorkingDirectory)/Elizium.FakeBuddy.nuspec'
          versioningScheme: byEnvVar
          versionEnvVar: buildVersion
          buildProperties: 'VERSIONHERE=$(buildVersion)'

      # - task: Pester@10
      #   inputs:
      #     scriptFolder: '$(System.DefaultWorkingDirectory)/$(moduleName)/Tests/*'
      #     resultsFile: '$(System.DefaultWorkingDirectory)/Test-Pester.XML'
      #     usePSCore: true
      #     PesterVersion: 'LatestVersion|OtherVersion'
      #     preferredPesterVersion: '5.0.3'
      #     additionalModulePath: '$(System.DefaultWorkingDirectory)/$(moduleName)/Output'
      #     ScriptBlock: '{ Set-location $(System.DefaultWorkingDirectory)/$(moduleName) }'
