# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Build.DefinitionName)_$(Date:yyyyMMdd))

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  major: 0
  minor: 0
  patch: $(Build.BuildID)
  buildVersion: $(major).$(minor).$(patch)
  system.debug: true

stages:
- stage: Build
  jobs:
    - job: Build
      steps:
      - powershell: ./bootstrap.ps1
        displayName: 'Install pre-requisites'
      - task: PowerShell@2
        displayName: 'Perform build'
        inputs:
          pwsh: true
          failOnStderr: true
          targetType: 'filePath'
          filePath: '$(System.DefaultWorkingDirectory)/do-build.ps1'
      - task: PowerShell@2
        displayName: 'Run Tests'
        inputs:
          pwsh: true
          failOnStderr: true
          targetType: 'filePath'
          filePath: '$(System.DefaultWorkingDirectory)/do-tests.ps1'
